import { useEffect, useState } from 'react';
import type { Preferences, Profile } from '../core/types';
import { viewportKey } from '../core/protocol';
import { Icon } from './Art';
type InstallPrompt = Event & { prompt: () => Promise<void> };
export default function Settings({ prefs, profiles, activeId, installPrompt, onInstall, onPrefs, onProfile, onAdd, onRename, onDelete, onClose }: {
  prefs: Preferences; profiles: Profile[]; activeId: string; installPrompt: InstallPrompt | null; onInstall: () => void;
  onPrefs: (p: Preferences) => void; onProfile: (id: string) => void; onAdd: (name: string) => void; onRename: (name: string) => void; onDelete: (id: string) => void; onClose: () => void;
}) {
  const [name, setName] = useState(''), [rename, setRename] = useState(profiles.find(p => p.id === activeId)?.name ?? ''), [confirm, setConfirm] = useState(false), [ruler, setRuler] = useState(189);
  const [kept, setKept] = useState<boolean | null>(null);
  const standalone = matchMedia('(display-mode: standalone)').matches || Boolean((navigator as Navigator & { standalone?: boolean }).standalone);
  const update = (patch: Partial<Preferences>) => onPrefs({ ...prefs, ...patch });
  useEffect(() => { void navigator.storage?.persisted?.().then(value => setKept(value)); }, []);
  return <main className="settings-page page-enter"><div className="section-heading align-left"><h1>Settings</h1><p>Set things up before a session. Your choices stay on this device.</p></div>
    <section className="settings-section"><h2>Profiles</h2><div className="settings-fields">
      <label>Current profile<select value={activeId} onChange={e => { onProfile(e.target.value); setRename(profiles.find(p => p.id === e.target.value)?.name ?? ''); setConfirm(false); }}>{profiles.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
      <form onSubmit={e => { e.preventDefault(); if (rename.trim()) onRename(rename.trim()); }}><label htmlFor="nickname">Nickname</label><div className="input-action"><input id="nickname" value={rename} maxLength={30} onChange={e => setRename(e.target.value)} required /><button className="button button-outline button-small">Save</button></div></form>
      <form onSubmit={e => { e.preventDefault(); if (name.trim()) { onAdd(name.trim()); setRename(name.trim()); setName(''); setConfirm(false); } }}><label htmlFor="new-gardener">Add a gardener</label><div className="input-action"><input id="new-gardener" value={name} placeholder="Choose a nickname" maxLength={30} onChange={e => setName(e.target.value)} required /><button className="button button-outline button-small">Add</button></div></form>
    </div><p className="small muted">Each gardener has a separate journal. A nickname is enough; no account needed.</p></section>
    <section className="settings-section"><h2>Training</h2><div className="settings-fields"><label>Training rounds<select value={prefs.rounds} onChange={e => update({ rounds: Number(e.target.value) })}>{[5, 10, 15, 20].map(n => <option key={n} value={n}>{n} rounds</option>)}</select></label><label>Starting sequence<select value={prefs.startSpan} onChange={e => update({ startSpan: Number(e.target.value) })}>{[2, 3, 4, 5, 6, 7].map(n => <option key={n} value={n}>{n} plants</option>)}</select></label><label>Delay before recall<select value={prefs.delayMs} onChange={e => update({ delayMs: Number(e.target.value) })}><option value={3000}>3 seconds · shorter practice</option><option value={5000}>5 seconds · everyday training</option><option value={15000}>15 seconds · longer retention</option></select></label></div><p className="small muted">Training adapts from your chosen sequence length. Memory check-ins use their own fixed settings: 15 rounds and a 15-second barn interval.</p></section>
    <section className="settings-section"><h2>Sound, movement & appearance</h2><label className="toggle-row"><span><strong>Gentle sound effects</strong><small>Soft feedback after sorting. Check-ins stay silent.</small></span><input type="checkbox" checked={prefs.sound} onChange={e => update({ sound: e.target.checked })} /></label><label className="toggle-row"><span><strong>Reduce movement</strong><small>Keep the garden still. Timed cues keep the same length.</small></span><input type="checkbox" checked={prefs.reducedMotion} onChange={e => update({ reducedMotion: e.target.checked })} /></label>
      <div className="appearance-field"><span><strong>Garden brightness</strong><small>The plants and peppers stay the same in every theme.</small></span>
        <div className="mode-selector appearance-selector" role="group" aria-label="Garden brightness">{([['system', 'Match device'], ['light', 'Light'], ['dark', 'Dark']] as const).map(([value, label]) => <button type="button" key={value} aria-pressed={prefs.theme === value} className={prefs.theme === value ? 'selected' : ''} onClick={() => update({ theme: value })}>{label}</button>)}</div>
      </div>
      <p className="small muted">The sun and moon at the top switch ivory and dusk. Choose Match device to follow this phone again.</p>
    </section>
    <details className="settings-section calibration"><summary>Optional garden-size calibration</summary><p>With a real ruler, adjust this line until it measures exactly 5 cm on your screen. The game requests a 16 cm garden, reduced if needed to keep the plants and controls on screen.</p><div className="ruler-line" style={{ width: ruler }}><span>5 cm</span></div><label>Calibration line width<input type="range" min="100" max="320" value={ruler} onChange={e => setRuler(Number(e.target.value))} /></label><div className="inline-actions"><button className="button button-outline button-small" onClick={() => update({ calibration: { pixelsPerCm: ruler / 5, viewport: viewportKey() } })}>Save calibration</button><button className="text-button" onClick={() => update({ calibration: null })}>Reset</button></div><p className="small muted">{prefs.calibration ? prefs.calibration.viewport === viewportKey() ? `Saved: ${prefs.calibration.pixelsPerCm.toFixed(1)} pixels/cm. Requested garden: ${Math.round(prefs.calibration.pixelsPerCm * 16)} px; actual size is recorded at play.` : 'Your screen or zoom changed. Please calibrate again.' : 'No physical-size calibration set.'}</p></details>
    <section className="settings-section"><h2>Install and offline</h2>
      <p>After one visit, you can reopen WorM without a network. Installing adds a Home Screen icon; it does not copy your garden to another device or the cloud. Chrome and the installed app share the same local records.</p>
      {!standalone && installPrompt && <div className="inline-actions"><button className="button button-outline button-small" onClick={() => { void installPrompt.prompt().then(() => onInstall()); }}>Add to Home Screen</button></div>}
      <p>On iPhone or iPad, open Share and choose Add to Home Screen. Older iOS versions may keep Safari and the Home Screen icon as separate gardens.</p>
      <div className="inline-actions"><button className="button button-outline button-small" onClick={() => { void navigator.storage?.persist?.().then(value => setKept(value ?? false)); }}>Ask this browser to keep garden data</button></div>
      <p className="small muted">{kept === null ? 'This browser has not yet said whether it will keep garden data if storage runs low.' : kept ? 'This browser has promised to keep garden data if it can.' : 'This browser has not promised to keep garden data if storage runs low.'}</p>
    </section>
    <section className="settings-section"><h2>Your data stays with you</h2><p>Session records are saved in this browser. Export a backup from your journal before clearing browser data or changing devices. There are no ads, trackers, or cloud accounts.</p>{!confirm ? <button className="text-button danger" onClick={() => setConfirm(true)}>Delete this gardener and their sessions…</button> : <div className="notice"><p>Delete <b>{profiles.find(p => p.id === activeId)?.name}</b> and all their saved sessions on this device? This cannot be undone.</p><div className="inline-actions"><button className="button button-danger button-small" onClick={() => { onDelete(activeId); setConfirm(false); }}>Delete gardener & sessions</button><button className="button button-outline button-small" onClick={() => setConfirm(false)}>Keep my data</button></div></div>}</section>
    <button className="button button-primary" onClick={onClose}>Back to garden <Icon name="arrow" /></button>
  </main>;
}
